export const MEMBERSHIP_ROLES = ['OWNER', 'ADMIN', 'EDITOR', 'VIEWER'] as const;
export type MembershipRole = (typeof MEMBERSHIP_ROLES)[number];

export const PERMISSIONS = [
  'GROUP_MANAGE',
  'MEMBERS_INVITE',
  'MEMBERS_REMOVE',
  'MEMBERS_UPDATE_ROLE',
  'TRANSACTIONS_READ',
  'TRANSACTIONS_CREATE',
  'TRANSACTIONS_UPDATE',
  'TRANSACTIONS_DELETE',
  'INVESTMENTS_READ',
  'INVESTMENTS_CREATE',
  'INVESTMENTS_UPDATE',
  'INVESTMENTS_DELETE',
  'CATEGORIES_MANAGE',
] as const;
export type Permission = (typeof PERMISSIONS)[number];

export const TRANSACTION_TYPES = ['INCOME', 'EXPENSE'] as const;
export type TransactionType = (typeof TRANSACTION_TYPES)[number];

export * from './auth';

export const ROLE_PERMISSIONS: Record<MembershipRole, readonly Permission[]> = {
  OWNER: PERMISSIONS,
  ADMIN: [
    'MEMBERS_INVITE',
    'MEMBERS_REMOVE',
    'MEMBERS_UPDATE_ROLE',
    'TRANSACTIONS_READ',
    'TRANSACTIONS_CREATE',
    'TRANSACTIONS_UPDATE',
    'TRANSACTIONS_DELETE',
    'INVESTMENTS_READ',
    'INVESTMENTS_CREATE',
    'INVESTMENTS_UPDATE',
    'INVESTMENTS_DELETE',
    'CATEGORIES_MANAGE',
  ],
  EDITOR: [
    'TRANSACTIONS_READ',
    'TRANSACTIONS_CREATE',
    'TRANSACTIONS_UPDATE',
    'INVESTMENTS_READ',
    'INVESTMENTS_CREATE',
    'INVESTMENTS_UPDATE',
    'CATEGORIES_MANAGE',
  ],
  VIEWER: ['TRANSACTIONS_READ', 'INVESTMENTS_READ'],
};
